es:
  image: elasticsearch
  ports: 
    - 9200:9200
  
loader:
  image: "data_loader-service:latest"
  ports:
    - 9090:9090
  links:
    - es:es
  environment:
    ES_CONN: "es:9200"

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - es:es
  environment:
    ELASTICSEARCH_URL: "http://es:9200"
